# Generated by Django 4.2 on 2023-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_area',
            name='link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
