# Generated by Django 4.2 on 2023-04-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cuponcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CuponCode',
            new_name='CouponCode',
        ),
    ]
